export const PRODUCT_LOAD_IN_PROGRESS = 'PRODUCT_LOAD_IN_PROGRESS';
export const PRODUCT_LOAD_FAIL = 'PRODUCT_LOAD_FAIL';
// export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const PRODUCT_ADD_BY_ID = 'PRODUCT_ADD_BY_ID';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCTS_BY_LIMIT = 'GET_PRODUCTS_BY_LIMIT';
export const LOADING = 'LOADING';